name: gratistellar
description: "Build a galaxy of gratitude with a peaceful gratitude tracker"
publish_to: "none"

version: 1.0.10+24
environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  vector_math: ^2.2.0
  package_info_plus: ^9.0.0
  firebase_crashlytics: ^5.0.3
  firebase_analytics: ^12.0.3
  device_info_plus: ^12.2.0
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.3

  # Data & storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  archive: ^4.0.7
  file_picker: ^8.1.6
  file_saver: ^0.3.1
  crypto: ^3.0.6

  # Firebase & Auth
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^7.2.0

  # UI & visuals
  flutter_svg: ^2.0.10
  provider: ^6.1.1
  share_plus: ^12.0.0
  flutter_dotenv: ^6.0.0
  url_launcher: ^6.2.2

  # Audio
  flutter_soloud: ^3.4.9

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/textures/
    - assets/fonts/
    - assets/icon_star.svg
    - assets/icon.png

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-VariableFont_wght.ttf

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/colour-icon.png"
  image_path: "assets/colour-icon.png"
  adaptive_icon_background: "#2E2466"
  adaptive_icon_foreground: "assets/colour-icon.png"
